### ISSUE TITLE
Error loading yolov3 weights: ValueError: Layer count mismatch when loading weights from file. Model expected 147 layers, found 217 saved layers.

### ISSUE THREAD

**Issue by RogerMor** [ruoxinx/site-dust-detect#1]
When trying to run the demo with the model downloaded from GoogleDrive: https://drive.google.com/file/d/1gICkxR5i4Qzt1yH-QsUsUKrUZTJGbm0S/view?usp=sharing

We get the following error:

ValueError: Layer count mismatch when loading weights from file. Model expected 147 layers, found 217 saved layers.

Could you please help us in this matter?

**Comment by ruoxinx** [comment]
I believe this error was caused by the different versions of Keras and TensorFlow. I have updated the requirement, and you should be able to solve this error, but let me know if there are any new issues.

**Comment by RogerMor** [comment]
> I believe this error was caused by the different versions of Keras and TensorFlow. I have updated the requirement, and you should be able to solve this error, but let me know if there are any new issues.

Thank you very much. I'm going to do the test with the versions reported and I will let you know if it works. Thanks again!

**Comment by RogerMor** [comment]
ValueError: You are trying to load a weight file containing 217 layers into a model with 147 layers.

The error persists. 

It seams that the h5 file of weights I'm using for yolov3 (downloaded from your google drive and named trained_weights_stage_1.h5) has 217 saved layers while the arquitecture of the YoloV3 provided in the code has 147 layers. Is like if the saved weights are not corresponding to the arquitecture provided.

**Comment by ruoxinx** [comment]
Thanks for your information. I just ran the code and it worked fine from my end. I re-uploaded the model weight file. Please kindly check.

**Comment by RogerMor** [comment]
Dear ruoxinx,

Thank you very much. I realized that the link of google dirive you provide:

https://drive.google.com/file/d/1hlTsxfvRwinzVdou8V4V1r3KXDYkmgko/view?usp=sharing

Still shows a model with last modification on 5 May 2021:

![image](https://user-images.githubusercontent.com/64934851/162144390-7f02555a-0fdc-4f40-bd3a-8d73e0082d63.png)

Maybe this is the problem?

With kind regards,

Roger.

**Comment by ruoxinx** [comment]
Thanks, I just downloaded this weight file from this link and ran it successfully on my local machine. I think it is the correct one. 
![Screenshot 2022-04-07 111940](https://user-images.githubusercontent.com/76619793/162234209-9e6c8029-e9ec-4171-b63e-cdb96a9885fb.png)
![Screenshot 2022-04-07 112332](https://user-images.githubusercontent.com/76619793/162234912-d00ba1c9-36bc-4fa6-a106-1aeccd0c3b82.png)

**Comment by RogerMor** [comment]
OK! Thanks. Then it is on my side to solve this. Thanks again!
