### ISSUE TITLE
Versions of Python, Keras and Tensorflow

### ISSUE THREAD

**Issue by RogerMor** [ruoxinx/site-dust-detect#2]
Could you please indecate which versions of Python, Keras and Tensorflow shall be used to run the code?

Thank you very much!

**Comment by ruoxinx** [comment]
Sure, you may check the installation requirements I updated:
python==3.6
tensorflow-gpu==1.13.2
keras==2.1.5

**Comment by RogerMor** [comment]
> Sure, you may check the installation requirements I updated: python==3.6 tensorflow-gpu==1.13.2 keras==2.1.5

Thank you very much for the information!
