### ISSUE TITLE
Arquitecture of the published Models?

### ISSUE THREAD

**Issue by RogerMor** [ruoxinx/site-dust-detect#3]
The access to the weights of the 3 models (SSD, Faster RCNN and Yolov3) are provided via Google Drive. However the exact architecture of the models is not provided.

¿Could you please provide the exact architecture of the 3 models?

Than you very much in advance!

**Comment by ruoxinx** [comment]
I used the default architecture of these classic models (SSD, Faster RCNN, and Yolov3) and you may find more details about these models in our paper. Let us know if you have any questions.

**Comment by RogerMor** [comment]
> I used the default architecture of these classic models (SSD, Faster RCNN, and Yolov3) and you may find more details about these models in our paper. Let us know if you have any questions.

Thank you very much!

**Comment by RogerMor** [comment]
> I used the default architecture of these classic models (SSD, Faster RCNN, and Yolov3) and you may find more details about these models in our paper. Let us know if you have any questions.

Thank you very much. I will look at that and let you know. I will close the issue as soon as I tested the three methods. Thanks again!

**Comment by RogerMor** [comment]
Dear ruoxinx,

In the paper of the SSD there are two different arquitectures. The SSD300 and the SSD512. Could you please indicate which one corresponds to the weights you provide in Google Drive for the SSD? 

Thank you very much in advance

**Comment by ruoxinx** [comment]
We mentioned this in our paper and we are using SSD-300 model.

**Comment by RogerMor** [comment]
> We mentioned this in our paper and we are using SSD-300 model.

Perfect! Thank you very much!

**Comment by RogerMor** [comment]
I Just want to  mention you that I succeeded running the ssd:

![image](https://user-images.githubusercontent.com/64934851/162157296-8822fa8f-bd02-4a23-9b4e-7447debab5cb.png)

Thank you very much!

I'm wondering if I shall use some specific parameters for the detection such as ancors, to reproduce exactly your reults. ¿Or you think that with the default parameters I'm using for the SSD its enough?

Thanks a lot!

**Comment by ruoxinx** [comment]
Great, you may use the default parameters of the SSD except I set the IoU to 0.3 as indicated in the paper. I also pasted my parameter settings here for your reference.

> class SSD(object):

    _defaults = {
        "model_path"        : 'model_data/ep082-loss1.643-val_loss1.545.h5',
        "classes_path"      : 'model_data/voc_classes.txt',
        "input_shape"       : (300, 300, 3),
        "confidence"        : 0.5,
        "nms_iou"           : 0.3,
        'anchors_size'      : [30,60,111,162,213,264,315],
        "letterbox_image"   : False,
    }

**Comment by RogerMor** [comment]
Dear ruoxinx,

Thank you very much for this information!

With best regards,

Roger.

**Comment by RogerMor** [comment]
Dear ruoxinx,

I let you know that I succeeded using the Faster-rcnn with your weights:

![51](https://user-images.githubusercontent.com/64934851/162386302-c92d5523-bffc-48af-ab25-3f1bb8148f7c.png)

I'm wondering if you are using the same anchors and thresholds than for the SSD or you have a specific set of parameters of the Faster-RCNN. ¿Could you please help me in this matter?

Thank you so much in advance!

**Comment by ruoxinx** [comment]
Cool! I used the default parameters in Faster RCNN while setting the iou to 0.3 as well.
